---
title: "Graficos"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gráficos con la función `plot`

```{r primero_plot, fig.cap="Gráfico básico de puntos explicando el uso del plot", fig.align='center'}
alumnos = c(1:10)
notas = c(4,7,8,5,9,8,7,7,10,6)
plot(alumnos,notas)
```

Si no incorporamos vector `y`, `R` nos va a tomar el parámetro `x` como si fuese el vector de datos `y` : `plot(1:n, x)`

```{r}
plot(2^(1:6))
```

Si queremos representar una función $f(x)$:

```{r}
f <- function(x){sqrt(x)}
plot(f)
```

## Parámetros

```{r}
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n-(1/sqrt(5))*((1-sqrt(5))/2)^n
fib
par(mfrow = c(1,2))
plot(fib, xlab="n", ylab= expression(F[n]),
     main = "Sucesión de Fibonacci", pch = 21, cex = 1, col = "black", bg = "palegoldenrod", log = "xy")
par(mfrow = c(1,1))
```

## Escála logarítmica

```{r}
par(mfrow = c(1,2))
plot = plot(exp(1:20), xlab = "Indice", ylab = expression(e^{1:20}),
            main = "Escala lineal")
plotLog = plot(exp(1:20), log = "y", xlab = "Indice",
               ylab = expression(e^{1:20}), 
               main = "Escala logarítmica en el eje y")
par(mfrow = c(1,1))
```

## Tipos de gráfico
```{r}
par(mfrow = c(3,2))
x = c(50:59)
y = c(2,9,25,3,100,77,62,54,19,40)
plot(x,y, main="Nube de puntos = p", pch = 21, cex = 2, col = "blue", type = "p")
plot(x,y, main="Lineas = l", pch = 21, cex = 2, col = "blueviolet", type = "l")
plot(x,y, main="Lineas con puntos = b", pch = 21, cex = 2, col = "gold", type = "b")
plot(x,y, main="Lineas atravezando los puntos = o", pch = 21, cex = 2, col = "deeppink", type = "o")
plot(x,y, main="Histograma de lineas verticales = h", pch = 21, cex = 2, col = "springgreen", type = "h",)
plot(x,y, main="Histograma de escalones = s", pch = 21, cex = 2, col = "firebrick1", type = "s")
par(mfrow = c(1,1))
```

```{r}
x = (2*(1:20))
y = (-1)^(1:20)*5*(1:20)
plot(x, y, main="Ejemplo de grafico", pch=20, cex=1, type="b", lty=4, lwd=2, xaxp=c(0,40,2), yaxp=c(-100,100,8))
```

```{r}
plot(n, fib, pch=20, col="black",cex=1.2, type="o",lty="dashed", lwd=2, xlim=c(0,20), ylim=c(0,6000), xaxp=c(0,20,8),yaxp=c(0,6000,12))
```

## ?plot
## ?par
